### ISSUE TITLE
while running the demo_server file, I am getting the error

### ISSUE THREAD

**Issue by artinegi1607** [VaibhavAbhimanyooHiwase/DeepSpeech2#1]
Traceback (most recent call last):
  File "deploy/demo_server.py", line 601, in <module>
    main()
  File "deploy/demo_server.py", line 597, in main
    start_server(kwargs)
  File "deploy/demo_server.py", line 504, in start_server
    vocab_list)
  File "/home/arti/nlp_engine/GIT/deepspeech2_python3/DeepSpeech2/DeepSpeech/deploy/../model_utils/model.py", line 478, in init_ext_scorer
    language_model_path, vocab_list)
  File "/home/arti/nlp_engine/GIT/deepspeech2_python3/DeepSpeech2/DeepSpeech/deploy/../decoders/swig_wrapper.py", line 23, in __init__
    swig_decoders.Scorer.__init__(self, alpha, beta, model_path, vocabulary)
  File "/home/arti/nlp_engine/GIT/deepspeech2_python3/DeepSpeech2/DeepSpeech/deploy/../swig_decoders.py", line 1140, in __init__
    _swig_decoders.Scorer_swiginit(self, _swig_decoders.new_Scorer(alpha, beta, lm_path, vocabulary))
TypeError: in method 'new_Scorer', argument 4 of type 'std::vector< std::string,std::allocator< std::string > > const &'

**Comment by VaibhavAbhimanyooHiwase** [comment]
@artinegi1607 can you give me python3 version?

**Comment by artinegi1607** [comment]
python3.6.9

**Comment by VaibhavAbhimanyooHiwase** [comment]
Can you use Ubuntu 16.04 with pre-installed python 3.5.2?
